# Generated by Django 4.2.21 on 2025-06-15 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Harcama', 'verbose_name_plural': 'Harcamalar'},
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 15, 9, 18, 4, 145838, tzinfo=datetime.timezone.utc), verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Yiyecek & İçecek'), ('transport', 'Ulaşım'), ('entertainment', 'Eğlence'), ('utilities', 'Faturalar'), ('shopping', 'Alışveriş'), ('health', 'Sağlık'), ('education', 'Eğitim'), ('housing', 'Konut'), ('clothing', 'Giyim'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Harcama Adı'),
        ),
    ]
